# Generated by Django 2.2.10 on 2020-03-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='tenant_id',
        ),
    ]
