# Generated by Django 2.2.10 on 2020-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Month')),
                ('order_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parcel_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_aud', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost AUD')),
                ('cost_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cost RMB')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Shipping Fee')),
                ('sell_price_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sell Price RMB')),
                ('profit_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profit RMB')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
