# Generated by Django 2.2.10 on 2020-02-28 05:48

import core.django.db
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.IntegerField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(blank=True, default=core.django.db.get_schema_name, max_length=32)),
                ('month', models.DateField(verbose_name='Month')),
                ('order_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parcel_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_aud', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost AUD')),
                ('cost_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cost RMB')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Shipping Fee')),
                ('sell_price_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sell Price RMB')),
                ('profit_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profit RMB')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
