# Generated by Django 2.2.10 on 2020-03-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin', models.TextField(blank=True, max_length=1024, verbose_name='pinyin')),
                ('name_cn', models.CharField(help_text='中文名称', max_length=255, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, help_text='英文名称', max_length=255, verbose_name='英文名称')),
                ('website', models.URLField(blank=True, help_text='官方网站地址', max_length=255, verbose_name='官网地址')),
                ('parcel_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='包裹数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(help_text='运单号', max_length=255, verbose_name='Track ID')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='is delivered')),
                ('last_track', models.CharField(blank=True, max_length=512, null=True, verbose_name='last track')),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='运费', max_digits=8, verbose_name='Shipping Fee')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='重量', max_digits=8, null=True, verbose_name='Weight')),
                ('id_upload', models.BooleanField(default=False, verbose_name='ID uploaded')),
                ('remarks', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remarks')),
                ('delivery_sms_sent', models.BooleanField(default=False, verbose_name='delivery sms')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('delivered_time', models.DateTimeField(blank=True, null=True, verbose_name='寄达时间')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Address', verbose_name='address')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='express.ExpressCarrier', verbose_name='carrier')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
