# Generated by Django 2.2.10 on 2020-03-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('express', '0001_initial'),
        ('carrier_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_orders', to='order.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='expresscarrier',
            name='tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_tracker.CarrierTracker'),
        ),
    ]
