# Generated by Django 2.2.10 on 2020-03-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin', models.TextField(blank=True, max_length=1024, verbose_name='pinyin')),
                ('name_cn', models.CharField(help_text='中文名称', max_length=255, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, help_text='英文名称', max_length=255, verbose_name='英文名称')),
                ('domain', models.CharField(blank=True, help_text='domain', max_length=512, verbose_name='domain')),
                ('website', models.URLField(blank=True, help_text='官方网站地址', max_length=255, verbose_name='官网地址')),
                ('search_url', models.URLField(blank=True, help_text='查询网页地址', max_length=1024, verbose_name='查询网址')),
                ('post_search_url', models.URLField(blank=True, help_text='查询提交网址', max_length=1024, verbose_name='查询提交网址')),
                ('need_id', models.BooleanField(default=False, help_text='是否需要身份证', verbose_name='需要身份证')),
                ('id_upload_url', models.URLField(blank=True, help_text='证件上传地址', max_length=1024, verbose_name='证件上传地址')),
                ('track_id_regex', models.CharField(blank=True, help_text='订单号正则表达式', max_length=512, verbose_name='单号正则')),
                ('last_track_id', models.CharField(blank=True, max_length=512, verbose_name='最后单号')),
                ('last_succeed_date', models.DateTimeField(blank=True, null=True, verbose_name='最后成功')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='别名')),
                ('selector', models.CharField(blank=True, default='table tr', max_length=255, verbose_name='CSS')),
                ('item_index', models.IntegerField(blank=True, default=-1, verbose_name='顺序')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
